//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuroTimePesonelTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Action_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action_tbl()
        {
            this.Reports_tbl = new HashSet<Reports_tbl>();
        }
    
        public int ID { get; set; }
        public Nullable<int> P_Id { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> Checkin_Time { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> Checkout_Time { get; set; }
        public string Shift { get; set; }
        public string Job_Rotation { get; set; }
        public string Description { get; set; }
        public string Cadre { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Dater { get; set; }
    
        public virtual Personel_tbl Personel_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports_tbl> Reports_tbl { get; set; }
    }
}
