//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuroTimePesonelTakipSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action_tbl> Action_tbl { get; set; }
        public virtual DbSet<Admin_tbl> Admin_tbl { get; set; }
        public virtual DbSet<Department_tbl> Department_tbl { get; set; }
        public virtual DbSet<Personel_tbl> Personel_tbl { get; set; }
        public virtual DbSet<Reports_tbl> Reports_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
