//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuroTimePesonelTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel_tbl()
        {
            this.Action_tbl = new HashSet<Action_tbl>();
            this.Admin_tbl = new HashSet<Admin_tbl>();
            this.Reports_tbl = new HashSet<Reports_tbl>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Sicil_No { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> D_Id { get; set; }
        public string Position { get; set; }
        public string Staff { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_tbl> Action_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_tbl> Admin_tbl { get; set; }
        public virtual Department_tbl Department_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports_tbl> Reports_tbl { get; set; }
    }
}
