//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuroTimePesonelTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports_tbl
    {
        public int ID { get; set; }
        public Nullable<int> P_Id { get; set; }
        public Nullable<int> A_Id { get; set; }
    
        public virtual Action_tbl Action_tbl { get; set; }
        public virtual Personel_tbl Personel_tbl { get; set; }
    }
}
